theme = "solarized-dark"
icons = "awesome5"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format_mem = "{Mug}/{MTg} GB({Mupi}%)"
format_swap = "{SUg}/{STg} GB({SUpi}%)"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "UTC %Y-%m-%d %R"
timezone = "Etc/UTC"
# locale = "en_AU"

[[block]]
block = "time"
interval = 60
format = "LOCAL %a %Y-%m-%d %R"
# locale = "en_AU"
timezone = "Australia/Melbourne"