theme = "solarized-dark"
icons = "awesome5"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
format_mem = "{mem_used;G}/{mem_total;G}({mem_used_percents})"
format_swap = "{swap_used;G}/{swap_total;G}({swap_used_percents})"
display_type = "memory"
icons = true
clickable = true
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 1
format = "{barchart} {utilization} {frequency}"

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "net"
device = "wlp0s20f3"
format = "{signal_strength} {speed_down;K*b} {graph_down;K}"
interval = 5

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "UTC %Y-%m-%d %R"
timezone = "Etc/UTC"
# locale = "en_AU"

[[block]]
block = "bluetooth"
mac = "E8:81:EB:15:51:65"
# label = "MX Master 3"

[[block]]
block = "time"
interval = 60
format = "LOCAL %a %Y-%m-%d %R"
# locale = "en_AU"
timezone = "Australia/Melbourne"

[[block]]
block = "battery"
interval = 10
format = "{percentage}% {time}"

[[block]]
block = "xrandr"
icons = true
# resolution = true
interval = 2